ingress:
  # domain: clap.example.com # Required
  # clusterIssuer: zerossl

replicaCount: 1

image:
  repository: ghcr.io/austien/clapbot
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    memory: 128Mi
  requests:
    cpu: 20m
    memory: 30Mi

nodeSelector: {}

tolerations: []

affinity: {}
