apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  {{- if .Values.ingress.clusterIssuer }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.ingress.clusterIssuer }}
  {{- end }}
  name: {{ include "clapbot.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  ingressClassName: nginx
  rules:
  - host: {{ required "you need to add a domain, yo" .Values.ingress.domain }}
    http:
      paths:
      - backend:
          service:
            name: {{ include "clapbot.fullname" . }}
            port:
              number: 80
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - {{ .Values.ingress.domain }}
    secretName: {{ .Values.ingress.domain | replace "." "-" }}-tls
